name: Git Scout Analytics

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, master, develop]
  workflow_dispatch:  # Manual trigger

permissions:
  contents: read
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Repository Analytics
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: fetch full history
      
      - name: Run Git Scout Analysis
        uses: malcohelper/git-scout-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          command: 'stats --since 7d --json'
          post-comment: true
          quality-gate: true
          quality-threshold: 70
          fail-on-quality: false
