name: Weekly Analytics Report

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: "*/5 * * * *"   # chạy mỗi 5 phút
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: read

jobs:
  weekly-report:
    runs-on: ubuntu-latest
    name: Generate Weekly Report

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate and Send Weekly Report
        uses: malcohelper/git-scout/.github/actions/git-scout@main
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          report-title: "Weekly Analytics Report"
          slack-username: "Git Scout Bot"
          slack-channel: "news-daily" # Optional: override webhook's default channel
